name: 'C++ Py Auto-Format (clang-format and black automation and checks)'
description:
  C++ Py Auto-Format provides the ability to both auto-format your code, and to
  check that your code is formatted.
inputs:
  token:
    description:
      The token used to authenticate with GitHub.
    required: true
  clangFormatVersion:
    description:
      Major Clang Version number. Supports clang 14 to 20. Default 18
    required: false
    default: '18'
  include_c:
    description:
      Comma-separated list of file globs (e.g '**/*.cpp,**/*.hpp') that
      matches which tracked files should be formatted.
    required: false
    default:
      '**/*.c,**/*.h,**/*.C,**/*.H,**/*.cpp,**/*.hpp,**/*.cxx,**/*.hxx,**/*.c++,**/*.h++,**/*.cc,**/*.hh'
  include_py:
    description:
      Comma-separated list of file globs (e.g '**/*.py') that
      matches which tracked files should be formatted.
    required: false
    default:
      '**/*.py'
  exclude:
    description:
      Comma-separate list of files globs that indicate which files should
      not be formatted.
    required: false
    default: '""'
runs:
  using: 'docker'
  image: docker://ghcr.io/pgrete/cpp-py-formatter:latest
  args:
  - --github-token
  - ${{ inputs.token }}
  - --clang-format-version
  - ${{ inputs.clangFormatVersion }}
  - --include
  - ${{ inputs.include_c }}
  - --py_include
  - ${{ inputs.include_py }}
  - --exclude
  - ${{ inputs.exclude }}
  - check
branding:
  icon: 'align-left'
  color: 'red'
